apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yj7q3886q-go 
  janus-idp.io/tekton: yj7q3886q-go
  backstage.io/kubernetes-id: yj7q3886q-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yj7q3886q-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml